# Generated by Django 3.1.2 on 2021-06-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='nation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('LB', 'no idea')], default='LB', max_length=100),
        ),
    ]
