# Generated by Django 3.2.4 on 2021-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_readapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('RB', 'Right Backs'), ('LB', 'Left Backs'), ('RWB ', 'Right Wing Backs'), ('LWB ', 'Left Wing Backs'), ('CB', 'Centre Back'), ('CDM', 'Centre Defensive Midfielder'), ('CM', 'Centre Midfielder'), ('CAM', 'Centre Attacking Midfielder'), ('RM', 'Right Midfielder'), ('LM', 'Left Midfielder'), ('RW', 'Right Wing'), ('LW', 'Left Wing'), ('RF', 'Right Forwards'), ('LF', 'Left Forwards'), ('CF', 'Centre Forward'), ('ST', 'Striker')], default='LB', max_length=100),
        ),
    ]
